export { default as Navbar } from "./navbar/Navbar"
export { default as Login } from "./login/Login"
export { default as AdminDashboard } from "./dashboard/AdminDashboard"
export { default as MemberDashboard } from "./dashboard/MemberDashboard"
export { default as TrainerDashboard } from "./dashboard/TrainerDashboard"
export { default as Calendar } from "./calendar/Calendar"
export { default as Routines } from "./routines/Routines"
export { default as Column } from "./column/Column"
export { default as Exercise } from "./exercise/Exercise"

// export { default as Component } from "./folder/component"